### ISSUE TITLE
Failed to compile on armbian

### ISSUE THREAD

**Issue by A-nemon-e** [noob404yt/mt7668-wifi-bt#1]
Hello,
I wonder if this driver is suitable for Android boxes running the mainline Linux kernel based on ARM64 but not x86. Actually I'm trying to compile it on armbian 23.08 (kernel version 5.15.130 from https://github.com/ophub/kernel/) but failed.
I got this error when compiling MT7668-WiFi:
```
 CC [M]  /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/gl_init.o
In file included from /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/include/gl_os.h:197,
                 from /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/gl_init.c:73:
/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/version.h:87:29: error: expected declaration specifiers or '...' before string constant
   87 | #define NIC_NAME            "MT6632"
      |                             ^~~~~~~~
/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/gl_init.c:113:25: note: in expansion of macro 'NIC_NAME'
  113 | MODULE_SUPPORTED_DEVICE(NIC_NAME);
      |                         ^~~~~~~~
/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/gl_init.c:372:10: error: 'struct cfg80211_ops' has no member named 'mgmt_frame_register'
  372 |         .mgmt_frame_register = mtk_cfg80211_mgmt_frame_register,
      |          ^~~~~~~~~~~~~~~~~~~
make[2]: *** [scripts/Makefile.build:289: /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/os/linux/gl_init.o] Error 1
make[1]: *** [Makefile:1907: /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.15.130-ophub'
make: *** [Makefile.x86:50: driver] Error 2
```
 Being a complete novice, I wonder whether I did something wrong or ARM64 is just not yet supported.
My box information:
```
Model: E900V21E
CPU: S905L2
WiFi: MT7668RSN
```
It came with the Android system originally, but I flashed Armbian into it following the instructions from [this repo]( https://github.com/ophub/amlogic-s9xxx-armbian).

**Comment by noob404yt** [comment]
The open-source driver presently works on kernel 5.4 and will require changes at both the kernel level and within the driver code to get it working on 5.15 or higher.

**Comment by A-nemon-e** [comment]
I failed to compile on kernel 5.4 either.  Got this err:
```
root@armbian:~/mt7668-wifi-bt-main/MT7668-WiFi# make EXTRA_CFLAGS="-w" CROSS_COMPILE= -f Makefile.x86
cd /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan && make -C /lib/modules/5.4.256-ophub/build M=/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan PLATFORM_FLAGS="" modules
make[1]: Entering directory '/usr/src/linux-headers-5.4.256-ophub'
DCFG_SUPPORT_CHNL_CONFLICT_REVISE=0
DCFG_SUPPORT_AEE=0
HIF=sdio
DCFG_SUPPORT_CHNL_CONFLICT_REVISE=0
DCFG_SUPPORT_AEE=0
HIF=sdio
  Building modules, stage 2.
  MODPOST 1 modules
make[3]: *** No rule to make target 'arch/arm64/kernel/module.lds', needed by '/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/wlan_mt76x8_sdio.ko'.  Stop.
make[2]: *** [scripts/Makefile.modpost:94: __modpost] Error 2
make[1]: *** [Makefile:1663: modules] Error 2
make[1]: Leaving directory '/usr/src/linux-headers-5.4.256-ophub'
make: *** [Makefile.x86:50: driver] Error 2
```
At first I saw this comment https://github.com/Mange/rtl8192eu-linux-driver/issues/205#issuecomment-736366347 but found no module.lds.S in /scripts in kernel 5.4, as is shown in https://github.com/torvalds/linux/tree/v5.4/scripts. Were there any steps that I missed?

Anyway I succeeded in compiling the Wifi driver of MT7668 (on kernel 5.10) using[ this repo](https://github.com/yHpgi/MT7668/tree/k5.10). Its code had been updated to suit 5.10. 
Thank you for the detailed instructions on https://ps4linux.com/mt7668-wifi-bluetooth-drivers-linux-compile/ , otherwise I would have to spend much more time dealing with the challenges. 😆

**Comment by boza111** [comment]
> I failed to compile on kernel 5.4 either. Got this err:
> 
> ```
> root@armbian:~/mt7668-wifi-bt-main/MT7668-WiFi# make EXTRA_CFLAGS="-w" CROSS_COMPILE= -f Makefile.x86
> cd /root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan && make -C /lib/modules/5.4.256-ophub/build M=/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan PLATFORM_FLAGS="" modules
> make[1]: Entering directory '/usr/src/linux-headers-5.4.256-ophub'
> DCFG_SUPPORT_CHNL_CONFLICT_REVISE=0
> DCFG_SUPPORT_AEE=0
> HIF=sdio
> DCFG_SUPPORT_CHNL_CONFLICT_REVISE=0
> DCFG_SUPPORT_AEE=0
> HIF=sdio
>   Building modules, stage 2.
>   MODPOST 1 modules
> make[3]: *** No rule to make target 'arch/arm64/kernel/module.lds', needed by '/root/mt7668-wifi-bt-main/MT7668-WiFi/drv_wlan/MT6632/wlan/wlan_mt76x8_sdio.ko'.  Stop.
> make[2]: *** [scripts/Makefile.modpost:94: __modpost] Error 2
> make[1]: *** [Makefile:1663: modules] Error 2
> make[1]: Leaving directory '/usr/src/linux-headers-5.4.256-ophub'
> make: *** [Makefile.x86:50: driver] Error 2
> ```
> 
> At first I saw this comment [Mange/rtl8192eu-linux-driver#205 (comment)](https://github.com/Mange/rtl8192eu-linux-driver/issues/205#issuecomment-736366347) but found no module.lds.S in /scripts in kernel 5.4, as is shown in https://github.com/torvalds/linux/tree/v5.4/scripts. Were there any steps that I missed?
> 
> Anyway I succeeded in compiling the Wifi driver of MT7668 (on kernel 5.10) using[ this repo](https://github.com/yHpgi/MT7668/tree/k5.10). Its code had been updated to suit 5.10. Thank you for the detailed instructions on https://ps4linux.com/mt7668-wifi-bluetooth-drivers-linux-compile/ , otherwise I would have to spend much more time dealing with the challenges. 😆

Hello Your link to the repo of the driver which you used doesn't exist. Do you have a copy somewhere?
